### ISSUE TITLE
error generated from clonevol to fishplot

### ISSUE THREAD

**Issue by haoecust** [chrisamiller/fishplot#12]
Hi Chrisamiller,

I came accorss an error like "Error in if (yst > 85 | yst < 15) { : missing value where TRUE/FALSE needed  ", when importing clonevol results to fishplot. Would you help me to fix it.

Thanks
Best 
Hao

Here is my code and input data.

code:
library(clonevol)
library(fishplot)
data_demo = read.table('demo.tsv', header = T, sep = "\t")
data_demo <- data_demo[order(data_demo$cluster),]
vaf.col.names = grep('.vaf', colnames(data_demo), value=T)
sample.names <- gsub('.vaf', '', vaf.col.names)
clone.colors = NULL
sample.groups <- c('Start','Time1','Time2','Time3','Time4','Time5')
names(sample.groups) <- vaf.col.names

y = infer.clonal.models(variants = data_demo,
cluster.col.name = 'cluster',
ignore.clusters = NULL,
vaf.col.names = vaf.col.names,
ccf.col.names = NULL,
sample.groups = sample.groups,
cancer.initiation.model='monoclonal',
subclonal.test = 'bootstrap',
subclonal.test.model = 'non-parametric',
num.boots = 1000,
founding.cluster = 1,
cluster.center = 'mean',
clone.colors = clone.colors,
min.cluster.vaf = 0.01,
sum.p = 0.05,
alpha = 0.05)
#Mapping driver gene onto the evolutional tree
y <- transfer.events.to.consensus.trees(y,
data_demo[data_demo$is.driver,],
cluster.col.name = 'cluster',
event.col.name = 'gene')

f = generateFishplotInputs(results=y)
fishes = createFishPlotObjects(f)
 
## plot each of these with fishplot
pdf('fish.pdf', width=8, height=4)
for (i in 1:length(fishes)){
    fish = layoutClones(fishes[[i]])
    fish = setCol(fish,f$clonevol.clone.colors)
    fishPlot(fish,shape="spline", title.btm="PatientID", cex.title=0.7,
             vlines=seq(1, length(vaf.col.names)), vlab=vaf.col.names, pad.left=0.5)
}
dev.off()

data-------demo.tsv

mutation_id	cluster	gene	is.driver	A11.vaf	SP.vaf	Xp2.vaf	Xp3.vaf	Xp5.vaf	Xp6.vaf
GPR4:FALSE	1	GPR4	FALSE	19.8	40	43.93	44.74	49.53	42.86
KRTAP24-1:FALSE	1	KRTAP24-1	FALSE	33.33	22.58	41.28	48.48	41.61	64.18
MLANA:FALSE	1	MLANA	FALSE	23.26	87.5	81.48	100	100	100
PDP2:TRUE	1	PDP2	TRUE	37.5	27.27	87.23	100	98.86	100
PGAP1:FALSE	1	PGAP1	FALSE	0	44.44	58.82	64.29	24	62.5
SPIRE2:FALSE	1	SPIRE2	FALSE	26.15	48.68	76.14	100	97.2	97.06
ZNF860:FALSE	1	ZNF860	FALSE	25.71	19.05	67.69	100	100	100
DNAH14:FALSE	1	DNAH14	FALSE	41.51	52.27	53.16	56.06	53.93	66.67
HEATR2:FALSE	1	HEATR2	FALSE	41.67	31.71	65.32	80.46	69.08	67.65
NDUFA7:FALSE	1	NDUFA7	FALSE	39.19	57.14	64.44	100	100	100
NDUFV1:FALSE	1	NDUFV1	FALSE	18.6	24.14	43.48	46.97	30.57	24
NRG2:FALSE	1	NRG2	FALSE	30.3	53.49	56.14	59.55	53.21	56.14
PTPRF:FALSE	1	PTPRF	FALSE	23.27	51.04	42.11	55.15	49.11	51.52
RELN:FALSE	1	RELN	FALSE	22.16	40	38.53	49.53	48.27	50.72
TFR2:FALSE	1	TFR2	FALSE	24.23	49.57	43.18	54.9	51.9	50
ZNF658:FALSE	1	ZNF658	FALSE	44.44	36.36	50	51.72	63.46	62.5
CEP89:FALSE	1	CEP89	FALSE	20.25	40	51.28	49.4	40.77	45
DCAF4:FALSE	1	DCAF4	FALSE	36.13	50.51	84.82	100	100	98
DZIP1:FALSE	1	DZIP1	FALSE	19.12	34.78	33.33	62.5	51.91	43.24
EVA1B:FALSE	1	EVA1B	FALSE	22.25	42.59	44.56	49.77	52.22	47.27
HACL1:FALSE	1	HACL1	FALSE	21.69	13.95	47.62	51.25	52.03	35.71
KBTBD7:FALSE	1	KBTBD7	FALSE	96.3	64	100	100	100	100
LRRK2:FALSE	1	LRRK2	FALSE	28.07	39.62	43.64	49.37	46.21	39.22
LTBP2:FALSE	1	LTBP2	FALSE	29.37	30.77	69.9	100	100	100
MUC6:FALSE	1	MUC6	FALSE	12.93	13.85	26.13	25.93	26.29	34.12
TRPM4:FALSE	1	TRPM4	FALSE	18.55	44.29	54.95	45.71	51.13	54.67
ZNF862:FALSE	1	ZNF862	FALSE	12.2	50.91	42.14	53.09	51.49	54.24
CEMIP:FALSE	1	CEMIP	FALSE	31.58	31.03	75.31	100	100	100
CHSY1:FALSE	1	CHSY1	FALSE	27.27	24.49	83.61	100	98.63	100
FAM196B:FALSE	1	FAM196B	FALSE	19.44	15.79	44.87	57.14	47.83	53.33
DPCR1:FALSE	2	DPCR1	FALSE	0	16.67	17.14	0	0	0
DPCR1:FALSE	2	DPCR1	FALSE	0	50	69.23	0	0	0
GSC:FALSE	2	GSC	FALSE	0	35.29	0	0	0	0
LURAP1:FALSE	2	LURAP1	FALSE	23.29	63.64	51.69	59.26	47.88	60
SGTB:FALSE	2	SGTB	FALSE	0	30	0	0	0	0
SIGLEC11:FALSE	2	SIGLEC11	FALSE	0	20	0	0	0	0
SYTL2:FALSE	2	SYTL2	FALSE	18.35	47.62	47.93	40.71	34.81	26.56
TBC1D22A:FALSE	2	TBC1D22A	FALSE	0	44.74	0	0	0	0
ZNF587:FALSE	2	ZNF587	FALSE	0	55.17	0	0	0	0
ACOXL:FALSE	2	ACOXL	FALSE	25.36	53.04	51.15	51.23	48.4	40.91
ALDH18A1:FALSE	2	ALDH18A1	FALSE	14.29	15.38	15.25	0	0	0
ASNS:FALSE	2	ASNS	FALSE	20.49	60.78	55.15	50	48.03	45.45
FASN:TRUE	2	FASN	TRUE	30	55.56	47.46	36.11	42.34	36.59
FSCB:FALSE	2	FSCB	FALSE	0	100	100	90	0	100
FSCB:FALSE	2	FSCB	FALSE	0	30	0	0	0	0
PRKAG2:FALSE	2	PRKAG2	FALSE	0	13.79	0	0	0	0
SNAPC4:FALSE	2	SNAPC4	FALSE	0	38.71	0	0	0	0
TCF20:FALSE	2	TCF20	FALSE	0	40	0	0	0	0
TNFRSF25:FALSE	2	TNFRSF25	FALSE	0	14.29	0	0	0	0
CNDP2:FALSE	2	CNDP2	FALSE	0	42.86	0	0	0	0
IQSEC3:FALSE	2	IQSEC3	FALSE	0	22.22	0	0	0	0
MAP4:FALSE	2	MAP4	FALSE	0	18.03	17.53	23.81	0	0
SIDT2:FALSE	2	SIDT2	FALSE	0	23.08	0	0	0	0
TPCN1:FALSE	2	TPCN1	FALSE	0	9.8	0	0	0	0
HCN4:FALSE	2	HCN4	FALSE	0	34.09	0	0	0	0
BAI3:FALSE	3	BAI3	FALSE	21.13	52.78	41.94	50	53.44	40.48
EXOC3L2:FALSE	3	EXOC3L2	FALSE	0	12.9	0	0	14.52	0
MUC16:FALSE	3	MUC16	FALSE	0	57.5	18.87	21.3	23.31	15.38
RSPH1:FALSE	3	RSPH1	FALSE	26.26	47.41	38.87	44.44	51.46	46.85
ZNF208:FALSE	3	ZNF208	FALSE	0	30	16.13	0	23.08	0
ZNF493:FALSE	3	ZNF493	FALSE	0	30.77	0	35	25.45	15.15
ZNF493:FALSE	3	ZNF493	FALSE	14.29	30.77	0	34.15	25	14.71
ZNF493:FALSE	3	ZNF493	FALSE	0	25	0	26.67	20.63	0
ARVCF:FALSE	3	ARVCF	FALSE	0	9.3	0	0	0.58	0
CASKIN1:FALSE	3	CASKIN1	FALSE	13.95	75.56	61.54	65.38	61.84	66.67
FAM69B:FALSE	3	FAM69B	FALSE	0	21.43	0	0	0	0
LEMD3:FALSE	3	LEMD3	FALSE	24.06	59.68	41.24	61.11	56.96	48.28
OBSCN:FALSE	3	OBSCN	FALSE	23.63	58.08	42.62	53.08	45.92	50.27
PAF1:FALSE	3	PAF1	FALSE	0	50	29.09	48.15	34.25	52.38
SLC6A15:FALSE	3	SLC6A15	FALSE	25	66.67	31.58	42.11	44.44	70
TGDS:FALSE	3	TGDS	FALSE	29.73	67.5	45.95	44.58	46.3	41.3
ANKZF1:FALSE	3	ANKZF1	FALSE	0	13.64	0	0	0	0
C17orf59:FALSE	3	C17orf59	FALSE	0	49.32	0	0	0	0
MYH9:TRUE	3	MYH9	TRUE	0	37.78	0	0	0	0
PCDHA10:FALSE	3	PCDHA10	FALSE	22.31	51.82	42.34	51.08	52.84	43.21
TAB2:FALSE	3	TAB2	FALSE	0	15	0	0	0	0
TYW1:FALSE	3	TYW1	FALSE	0	75	36.36	62.5	53.33	0
ZNF469:FALSE	3	ZNF469	FALSE	0	48.57	0	0	0	0
FN1:FALSE	3	FN1	FALSE	13.21	88.46	36.54	45	57.97	34.62
NEFM:FALSE	3	NEFM	FALSE	0	40	0	0	0	0
PPP1R15B:FALSE	3	PPP1R15B	FALSE	26.01	54.78	34.84	48.02	49.88	48.25
PRG4:FALSE	3	PRG4	FALSE	0	15.79	0	0	0	0
SIGLEC1:FALSE	3	SIGLEC1	FALSE	20.6	54.63	41.84	40.89	49.38	49.26
TMCC3:FALSE	3	TMCC3	FALSE	23.03	60.53	41.11	48.95	49.43	46.15
DPCR1:FALSE	4	DPCR1	FALSE	21.05	20	0	0	18.52	20
STRA6:FALSE	4	STRA6	FALSE	0	40	0	0	0	0
CDH5:TRUE	4	CDH5	TRUE	0	47.71	0	0	0	0
DNM2:FALSE	4	DNM2	FALSE	21.74	44.83	15.79	24.58	18.86	21.62
HSPA2:FALSE	4	HSPA2	FALSE	0	44.44	0	0	0	0
TET2:FALSE	4	TET2	FALSE	18.75	46.67	0	0	0	0
TPX2:FALSE	4	TPX2	FALSE	0	12.5	0	0	0	0
U2SURP:FALSE	4	U2SURP	FALSE	0	17.5	0	0	0	0
ANKRD54:FALSE	4	ANKRD54	FALSE	0	15.79	0	0	0	0
ARHGEF10L:FALSE	4	ARHGEF10L	FALSE	0	15.71	0	0	0	0
MAMDC4:FALSE	4	MAMDC4	FALSE	0	15	0	0	0	0
ST3GAL5:FALSE	4	ST3GAL5	FALSE	46.67	57.14	50	70.59	45.45	0
TSNAXIP1:FALSE	4	TSNAXIP1	FALSE	0	31.25	0	0	0	0
DYSF:FALSE	4	DYSF	FALSE	0	14.29	0	0	0	0
OR52N4:FALSE	4	OR52N4	FALSE	0	34.09	0	0	0	0
SGMS2:FALSE	4	SGMS2	FALSE	34.21	46.67	0	0	0	0

**Comment by chrisamiller** [comment]
I was unable to replicate this with the information provided in the issue, but admittedly didn't spend too much time on it.  I realize the possibility is slim that you still care 4 years later (oof, sorry), but please feel free to reopen if you do!
