### ISSUE TITLE
Evaluation nested too deeply: infinite recursion

### ISSUE THREAD

**Issue by ghost** [chrisamiller/fishplot#13]
Dear chrisamiller,
I am trying to run fishplot but everytime I get this error of infinite recursion error. Also, could you please explain that should we consider VAF's in the matrix and what about the parents. I donot understand the parent column? What does this refer to?
My code is:
library(fishplot)
timepoints=c(0,300,500,700,1200)
frac.table = matrix(
    c(100,90,02,30,45,
	9,6,02,02,02,
	38,19,02,22,22,
	44,39,02,31,50,
	02,02,02,59,90),
ncol=length(timepoints))
parents = c(1,1,1,1)
fish = createFishObject(frac.table,parents,timepoints=timepoints, clone.labels=c("Subclone 1","Subclone 2","Subclone 3", "Subclone 4", "Subclone 5" ))
fish = layoutClones(fish)
sample.times = c(0,1200)
pdf("clonal.out.pdf",width=8,height=4)
fishPlot(fish,shape="spline",title.btm="Clonal",
         vlines=sample.times, vlab=sample.times, cex.title=0.5, bg.type="solid")
drawLegend(fish)
dev <- dev.off()

Error: evaluation nested too deeply: infinite recursion / options(expressions=)? Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?

**Comment by chrisamiller** [comment]
The parent vector describes the relationship of nested subclones.  For example, in this image (second plot on the README page):
https://camo.githubusercontent.com/8bf7791c59bf2669c9e39a7d00ea18454f871617/687474703a2f2f692e696d6775722e636f6d2f67594f323373692e706e67

The parental relationship looks like c(0,1,1,3).  That is, the founding clone (grey) has no parent clone, the purple subclone is derived from the grey clone, as is the orange subclone.  The yellow subclone is derived from the third (orange) subclone.  

Fix that parental vector and I imagine things will work.

**Comment by ghost** [comment]
Thank you for your suggestions. I did it finally. Here is the plot"
[Final Fish.pdf](https://github.com/chrisamiller/fishplot/files/2250582/Final.Fish.pdf)
