### ISSUE TITLE
Label clones with driver mutations

### ISSUE THREAD

**Issue by teng-gao** [chrisamiller/fishplot#15]
Is it possible to label clones with driver mutations like in Clonevol?

**Comment by chrisamiller** [comment]
Sorry that I missed this!  There isn't currently code for doing this, but it seems like a straightforward extension.  Realistically, I'm not going to get to it in the next few months, but I'd be happy to review and merge PRs, if you want to hack it in - Best of luck!

**Comment by teng-gao** [comment]
Submitted a pull request
https://github.com/chrisamiller/fishplot/pull/16

**Comment by chrisamiller** [comment]
merged - thanks!
