### ISSUE TITLE
fraction calculation and validateInput-error

### ISSUE THREAD

**Issue by fneuh** [chrisamiller/fishplot#18]
Hi Chris,

I wanted to run fishplot on a simulated dataset of 4 populations. The results of the simulation are cell counts, which I used to calculate fractions by taking the cell count of one population at each timepoint and dividing the total cell count of all 4 populations at that timepoint. Doing this for all populations and timepoints gives me the following fraction-table:

[frac.table.txt](https://github.com/chrisamiller/fishplot/files/2765042/frac.table.txt)

Is this how you even calculate the fractions? I couldn't find any details on this in the documentation or elsewhere.

Anyhow, if I continue with this fraction table, I get the following:

timepoints <- c(1,1000,2000,3000,4000,5000,6000,7000)
parents <- c(0,1,1,1)
fish <- createFishObject(frac.table, parents, timepoints = timepoints)
Error in validateInputs(frac.table, parents, nest.level, clone.labels,  : 
  clones with same parent cannot have values that sum to more than the percentage of the parent: Problem is in clusters  2,3,4 at timepoint 5

Could you help me on that?

Thanks,
Florian

**Comment by chrisamiller** [comment]
This is that 5th column:

```
35.82912
58.48916
5.681679
4.033901e-05
```

You say that the second cluster is contained within the first cluster, but it's VAF is higher!  If cluster 1 really is the founding event, then its fraction would be the fraction of cluster1_only plus the VAFs of any child clusters.  Does that help?

**Comment by fneuh** [comment]
Yes that helped, I excluded the first cluster from the plot and changed some bits and now it works fine.

Thanks for your help !
