### ISSUE TITLE
Error in validateInputs

### ISSUE THREAD

**Issue by DaringSky** [chrisamiller/fishplot#21]
Hi Chris,
It is very good to use Fishplot to describe the clonal evolution of tumors. But i have any questions.

1.How to understand the frac.table?
Can i use the average of variant allele frequency or cellular prevalence for each Cluster from SciClone/PyClone?

2.I have Error when i run the "createFishObject"
fish = createFishObject(frac.table,parents,timepoints=timepoints)
**Error in validateInputs(frac.table, parents, nest.level, clone.labels,  : 
  clones with same parent cannot have values that sum to more than the percentage of the parent: Problem is in clusters  2 at timepoint 2**
 Code is following:

> library(fishplot)
> timepoints=c(0,20,40,60)
> parents = c(0,1)
> frac.table = matrix(c(83,83,81,83,61,42,07,05),ncol=length(timepoints))
> fish = createFishObject(frac.table,parents,timepoints=timepoints)

i dont understand the error and i try to change the number of "clusters  2 at timepoint 2", but the error still exist.
Can you help me with this?

Thanks！！！
The Pyclone result (cluster and vaf)
[variant_allele_frequency.txt](https://github.com/chrisamiller/fishplot/files/3030076/variant_allele_frequency.txt)

**Comment by chrisamiller** [comment]
Yes, a reasonable estimate for each subclone is the mean VAF of all variants contained with in it. 


Here's what your data looks like as a matrix:

```
> matrix(c(83,83,81,83,61,42,07,05),ncol=4)
     [,1] [,2] [,3] [,4]
[1,]   83   81   61    7
[2,]   83   83   42    5
```

You're saying that the second subclone (row 2) is contained within subclone (row 1).  Yet, at the second timepoint, subclone 2 has with a higher VAF than the clone that contains it - That's an impossible situation!  Resolve that, and you should get some results.

**Comment by DaringSky** [comment]
Thank you for your answer！
I have a beautiful figure now.
