### ISSUE TITLE
Size of clone annotation labels in fishplot

### ISSUE THREAD

**Issue by davidkundrat** [chrisamiller/fishplot#25]
Good day to all!
I thought I would solve this easy problem myslef, but I cannot find a way to change the **size of clone annotation labels** that can be put into fishplot. I know how to change their color and angle but size option is not included in function **"createFishObject"**. I have tried to poke into **"fishPlot"** function as well, but there is no way of modifying this size as far as I know. I would be grateful for any suggestions/tips. Thanks for reply in advance.

Best regards,
David Kundrat

**Comment by chrisamiller** [comment]
Right, that's not a configurable option at present. Happy to accept pull requests if you'd like to hack that feature in!

**Comment by jenny-draper** [comment]
Hi Chris, I've got a fork that adds this functionality as well as a bit more, I was planning on submitting a pull request for it soon.

**Comment by chrisamiller** [comment]
fantastic! happy to look it over if you make a PR

**Comment by jenny-draper** [comment]
To anyone looking for this functionality, it should now be available via the argument **clone.annots.cex**; there's an example in the test file test.R

```
fish = createFishObject(frac.table,parents,
                        timepoints=timepoints, 
                        clone.labels=clone.labels, clone.annots=clone.annots, 
                        clone.annots.cex=1.5, clone.annots.pos=3, clone.annots.offset=0.5, clone.annots.col="blue")
```

**Comment by chrisamiller** [comment]
Closed in https://github.com/chrisamiller/fishplot/pull/26  Thanks again for the contribution!
