### ISSUE TITLE
SetCol Error in checkCol(fish) :    ERROR: number of colors must be equal to the number of clones

### ISSUE THREAD

**Issue by jkgopa** [chrisamiller/fishplot#28]
I was wondering if I could get some help resolving the following issue

When I try to use SetCol to create a custom color scheme I get the following error:
Error in checkCol(fish) : 
  ERROR: number of colors must be equal to the number of clones (11). Use the setCol() function to set an appropriate color scheme.

Here is the code I am running:
`
timepoints2=c(0,60,100)

frac.table2 = matrix(
  c(5, 5, 5, 5, 5, 5, 5, 5, 5, 5,5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,5,
    2.5, 2.5, 2.5, 2.5, 30, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5),
  ncol=length(timepoints2))

parents2 = c(0,0,0,0,0,0,0,0,0,0,0)

colors <- c("#ffffff","#f5f8fa","#e8f0f4","#d8e6ee","#c2dae6","#a7cce0",
            "#88beda","#5fb1d7","#06a3d7","#628ac3","#7874b9")

fish2 = createFishObject(frac.table2,parents2,timepoints=timepoints2)
setCol(fish2, colors)

fish2 = layoutClones(fish2)

fishPlot(fish2,shape="spline", vlines=c(0,100))`

When I run 'length(fish2@col)', I get a result of 1

**Comment by chrisamiller** [comment]
setCol returns the modified fish object, so you'll need 
```
fish2 = setCol(fish2, colors)
```
Hope this helps!

**Comment by jkgopa** [comment]
Yep, that did the trick.

Thanks!
