### ISSUE TITLE
Fishplot matrix rules

### ISSUE THREAD

**Issue by juberpatel** [chrisamiller/fishplot#29]
Hello,

Thanks for a really nice and useful visualization tool. I am trying to use it for my work. But the value matrix seems to be really finicky. For example, the Panel A example from test.R works fine but a slight change in the values gives error.

frac.table = matrix(
     c(100, 38, 34, 01,
       002, 00, 01, 00,
       003, 00, 01, 01,
       100, 00, 98, 30),
     ncol=length(timepoints))

I was wondering if there is a document stipulating all the constraints on the matrix values. That would be very helpful! It will allow me to create the fishplots that I need.

Thanks!

**Comment by chrisamiller** [comment]
The constraints are imposed by biology for the most part.  The error you're seeing is:

`Clone 4 goes from present to absent (fraction=0) and then back to present. Values for which the cluster was present must be non-zero. Either fix the inputs or set fix.missing.clones=TRUE to change offending timepoints to very small values.`

That's one such constraint. Another is that subclones cannot have greater VAFs than their parents.  A third is that two non-nested clones cannot have a sum greater than the value of their parent.  (you can't fit 30+20 inside of 40!)

These are mostly outlined in the validateInputs function here:
https://github.com/chrisamiller/fishplot/blob/master/R/object.R#L28

Best of luck!

**Comment by juberpatel** [comment]
Great! Thanks a lot.
