### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by kporkka** [chrisamiller/fishplot#3]
`fishPlot(fish,shape="spline",title.btm="633734",
         vlines=sample.times, vlab=sample.times, cex.title=0.5, bg.type="solid")`

should be

`fishPlot(fish,shape="spline",title.btm="633734",
         vlines=timepoints, vlab=timepoints, cex.title=0.5, bg.type="solid")`

A very nice package

**Comment by chrisamiller** [comment]
I think it's right as is. My intention was to label the points where samples were actually taken. The other two timepoints are there to provide the "bottleneck" shape that is assumed from the fact that the patient responded to therapy.  Thanks for the feedback, and glad the package is useful!

**Comment by kporkka** [comment]
Thanks for the reply. Indeed, error at my end, sorry :)
