### ISSUE TITLE
Save fish plot in interactive HTML

### ISSUE THREAD

**Issue by asancru** [chrisamiller/fishplot#32]
Hi, I'm a student finishing my Master thesis in Bioinformatics.

I am trying to create an interactive fish object (like `plotly`) to save it in HTML by using different packages (`htmltools::save_html`, `Hmisc::html`, `sink`, `plotly`, `html_plot`) but nothing is working. 

Is there any way to export fish plot as html?

**Comment by chrisamiller** [comment]
Unfortunately, I'm not sure how to go about that, but would welcome a pull request with that sort of option if you find something that works!
