### ISSUE TITLE
Clone showing up earlier than in the data

### ISSUE THREAD

**Issue by chrisleitzinger** [chrisamiller/fishplot#33]
Hi,

I have this data to plot:
```
timepoints <- c(-38, 0, 81, 368, 1011)
frac.table = matrix(
  c(0, 0, #-38
    0, 0, #0
    39.7, 0, #81
    48.1, 4.1, #368
    17, 0.0001),
  ncol=length(timepoints))
parents = c(0, 1)
fish = createFishObject(frac.table,parents,timepoints=timepoints,
                        col = c("darkblue", "#ffff3f"),
                        clone.labels = c("A", "B"))
fish = layoutClones(fish)

fishPlot(fish,shape="spline",title.btm= "Title",
         cex.title=1, vlines=c(timepoints), col.vline = "grey",
         vlab=c(timepoints), 
         bg.type = "solid",
         bg.col = "white"
)
```
This code gives me the below figure. As you can see the blue clone show up even before -38days when I set it up equal to 0.
![Screenshot2022_04_12_105709](https://user-images.githubusercontent.com/55062754/162991872-2bfdb739-dd29-4474-bfce-f0de6bf6c9c5.jpg)

Is it something I am missing?

Thanks!

**Comment by chrisamiller** [comment]
That happens because there is assumed "padding" before the first time point, since a tumor typically is assayed after it's already detectable. I believe the value must be non-zero, but passing `pad.left=0.01` to `fishplot()` (or some similarly small value) may give you what you want.
