### ISSUE TITLE
Questions about data input

### ISSUE THREAD

**Issue by xiw588** [chrisamiller/fishplot#34]
Hi, I am trying to apply fishplot() to my somatic mutation data. I have a couple of questions regarding the data input. I have MAF of somatic mutations, including variant allele fraction (VAF) and I am wondering if this applies to clonal fraction of each tumor cell population in your package. Also, can you please explain a bit on "a representation of descent in the form of parental relationships". 

Thank you.

**Comment by chrisamiller** [comment]
Before running fishplot, you'll need to do clonal inference on your data, to group mutations into subclones and determine the clonal fractions and how they change over time.  There are many tools for doing this, including sciclone, pairtree, pyclone, etc. This includes a need to build a phylogenetic tree describing the evolutionary relationships between subclones (which is descended from which).
