### ISSUE TITLE
Edit the colors of the fishplots

### ISSUE THREAD

**Issue by dan1medina** [chrisamiller/fishplot#36]
Hello Chris,

Thank you very much for this code. I would like to know how I can change the colors of the fishplots. I would like to change the order of grey, red, orange, yellow and maybe use a different ones. Thank you!

dan1medina

**Comment by chrisamiller** [comment]
Colors are set when the fish object is created via the `col` parameter. See `?createFishObject`
```
     col: A vector of colors to use when plotting each clone
```
Best of luck!
