### ISSUE TITLE
Error in if (yst > 85 | yst < 15)

### ISSUE THREAD

**Issue by LayalYasin** [chrisamiller/fishplot#39]
I am getting this error:

Error in if (yst > 85 | yst < 15) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In max(xpos) : no non-missing arguments to max; returning -Inf
2: In min(xpos) : no non-missing arguments to min; returning Inf

what does this error relate to ? and the warning messages ?

I have 56 clusters, two time points

 timepoints=c(1,2)  
frac.table = matrix(c(
1,56,0,0,0,2,36,0,0,0,0,0,0,0,3,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,36,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
90,4,0,0,1,0,3,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
),ncol=length(timepoints))

the first 28 clusters have no parent. the second 28 clusters have the previous 28 clusters as parents.
parents=c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28)

**Comment by chrisamiller** [comment]
Sorry, I am unable to reproduce this error using the information you've provided. Please include all of the exact code that you're running, followed by the resulting error message.

**Comment by LayalYasin** [comment]
thank you for the quick reply !

this is the exact code used:


```

 timepoints=c(2010,2011)  
frac.table = matrix(c(
1,56,0,0,0,2,36,0,0,0,0,0,0,0,3,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,36,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
90,4,0,0,1,0,3,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
),ncol=length(timepoints))


parents=c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28)


fish = createFishObject(frac.table,parents,timepoints=timepoints,fix.missing.clones = TRUE)

colors <- c("#D8E6EE", "#D6E4ED", "#D4E2EC", "#D2E0EB", "#D0DEEA", "#CEDCE9", "#CCDAE8", "#CAD8E7", "#C8D6E6", "#C6D4E5", "#C4D2E4", "#C2D0E3", "#C0CEE2", "#BECCD1", "#BCCAE0", "#BAC8DF", "#B8C6DE", "#B6C4DD", "#B4C2DC", "#B2C0DB", "#B0BEDA", "#AEBCD9", "#ACBAD8", "#AAB8D7", "#A8B6D6", "#A6B4D5", "#A4B2D4", "#A2B0D3","#FFA500", "#FFA400", "#FFA300", "#FFA200", "#FFA100", "#FFA000", "#FF9F00", "#FF9E00", "#FF9D00", "#FF9C00", "#FF9B00", "#FF9A00", "#FF9900", "#FF9800", "#FF9700", "#FF9600", "#FF9500", "#FF9400", "#FF9300", "#FF9200", "#FF9100", "#FF9000", "#FF8F00", "#FF8E00", "#FF8D00", "#FF8C00", "#FF8B00", "#FF8A00") 

fish = setCol(fish, colors)

fish = layoutClones(fish)

fishPlot(fish,shape="spline",title.btm="Sample1",
             cex.title=0.5, vlines=c(2011,2012), 
             vlab=c(“2010”,”2011”))



```

and this is the error and warning messages:
```

Error in if (yst > 85 | yst < 15) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In max(xpos) : no non-missing arguments to max; returning -Inf
2: In min(xpos) : no non-missing arguments to min; returning Inf
```

**Comment by chrisamiller** [comment]
Okay, I was able to diagnose and fix the issue.  I pushed some code and a new release that should address the issue. Thanks for the report, and good luck!

**Comment by LayalYasin** [comment]
thanks ! working perfectly now
