### ISSUE TITLE
Error in generating fish plots

### ISSUE THREAD

**Issue by alquamalok22** [chrisamiller/fishplot#41]
I have data for fish plot , that contains only timepoints and its frequency related to it and also the gene names, no ther inforation is there with me, regarding the parents(subclone) information. I need to know is its possible to generate the fishplot?  with this kind of data. PLease help...

**Comment by chrisamiller** [comment]
Fishplot assumes that you already have established clonal relationships and frequencies and would just like to plot them. Something like pairtree or sciclone may help with establishing clonal identities from sequencing data. Best of luck

**Comment by alquamalok22** [comment]
Thank you so much
