### ISSUE TITLE
error in layoutClones()

### ISSUE THREAD

**Issue by gunjangala** [chrisamiller/fishplot#7]
Hi Chris,
I encounter the following error(s) when I run layoutClones(). How can I fix this?
Following is the code I am trying to run:
```
> cp <- data.frame(cbind(0,clonalPlot[,c(7,8,9)]),stringsAsFactors = F)
> colnames(cp) <- c("G","GD","GB","GR")
> parents <- c(0,0,0,0)
> cp.matrix <- data.matrix(cp[1:5,])
> cp.matrix
 G GD    GB    GR
 0  0 0.000 0.737
 0  0 0.410 0.642
 0  0 0.436 0.524
 0  0 0.000 0.493
 0  0 0.431 0.458
> fish <- createFishObject(cp.matrix,parents,timepoints=c(0,10,20,30))
Error in ybtm[i, ] : subscript out of bounds
```
I guess the problem is "parents" variable. What if there is no information about "parental relationships between clones"? I tried:
```
> cp.matrix <- data.matrix(cp)
cp.matrix
G   GD   GB   GR
0 25.0  0.0  0.0
0  0.0  0.0 33.6
0  0.0 33.3 43.6
0  0.0 41.9 32.6
0 12.8 21.4  0.0
0  0.0 43.1 45.8
0  0.0 41.0 64.2
0  0.0  0.0 32.3
0  0.0 43.6 52.4
0  0.0 42.9  0.0
0 16.2 15.2  0.0
> parents <- c(rep(0,11))
> fish <- createFishObject(cp.matrix,parents)
Error in validateInputs(frac.table, parents, nest.level, clone.labels) : 
  clones with same nest level cannot have values that sum to more than 100%: Problem is in clusters  1,2,3,4,5,6,7,8,9,10,11
```

Thanks,
Gunjan

**Comment by chrisamiller** [comment]
You're going to have to provide more information, including some code that
allows me to reproduce the problem. Without that, there's nothing I can do
to help.

**Comment by gunjangala** [comment]
Hi Chris,
I am trying the exactly the same code mentioned earlier with ```cp.matrix``` as the input variable (output printed). We do not have information about parental relationships. What other information would you require?
Thanks,
Gunjan

**Comment by chrisamiller** [comment]
I'm sorry - the code didn't come through with the rest of the email notification! I'll take a look

**Comment by chrisamiller** [comment]
Yes, this is a simple problem. You have to provide parental relationships. If you don't have them, then you need to run your data through something like cloneEvol, SubcloneSeeker, etc, which can provide those phylogenies.
