### ISSUE TITLE
fishplot error (help wanted)

### ISSUE THREAD

**Issue by gyfangel** [chrisamiller/fishplot#8]
Hi,
   I used fishplot for  a test.
   The  input is like:
     frac.table=matrix(
       c(80,52,50,0,0,
       80,42,40,10,0,
       02,01,0,01,0,
       70,15,0,54,52,
       100,16,0,83,83),
        ncol=length(timepoints))
 
  I add a timepoint with vaf~0. and why the picture is at below (see the attachment : pic.png).

 How can I move the picture in the middle.
  
![pic](https://user-images.githubusercontent.com/31728766/30911156-1d971544-a3ba-11e7-9323-e6c93596cdde.png)
Thank you.
YF

**Comment by chrisamiller** [comment]
I need more information to answer this - can you paste the full series of commands that you're using and the ouput?

**Comment by gyfangel** [comment]
[test.r.txt](https://github.com/chrisamiller/fishplot/files/1337652/test.r.txt)
Hi,
Thanks for your reply. The commands I used can be found in the file attached (test.r).
The output is the picture.

**Comment by chrisamiller** [comment]
You don't have clones arising from independent events here, so you'll want to set the "separate.independent.clones" parameter to F.  Let me know if that doesn't solve the problem!
